# Generated by Django 5.0.6 on 2025-11-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BingoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(help_text='빙고판 순서를 위해 1~25 값을 사용하세요. 숫자가 낮을수록 위쪽/왼쪽에 배치됩니다.', unique=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(help_text='대시 없이 숫자만 입력하세요.', max_length=20)),
                ('team', models.CharField(choices=[('activity', '액티비티조'), ('culture', '문화탐방조'), ('food', '맛집탐방조')], max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
