# Generated by Django 5.0.6 on 2025-11-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bingoitem',
            options={'ordering': ['team', 'position']},
        ),
        migrations.AddField(
            model_name='bingoitem',
            name='team',
            field=models.CharField(choices=[('activity', '액티비티조'), ('culture', '문화탐방조'), ('food', '맛집탐방조')], default='activity', max_length=20),
        ),
        migrations.AlterField(
            model_name='bingoitem',
            name='position',
            field=models.PositiveIntegerField(help_text='빙고판 순서를 위해 1~9 값을 사용하세요. 숫자가 낮을수록 위쪽/왼쪽에 배치됩니다.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.CharField(choices=[('activity', '액티비티조'), ('culture', '문화탐방조'), ('food', '맛집탐방조')], default='activity', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='bingoitem',
            constraint=models.UniqueConstraint(fields=('team', 'position'), name='unique_position_per_team'),
        ),
    ]
