# Generated by Django 5.0.6 on 2025-11-28 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_bingoitem_options_bingoitem_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BingoSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('activity', '액티비티조'), ('culture', '문화탐방조'), ('food', '맛집탐방조')], default='activity', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('photo', models.FileField(upload_to='bingo_photos/')),
                ('status', models.CharField(choices=[('pending', '검토중'), ('approved', '승인')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bingo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='members.bingoitem')),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_submissions', to='members.member')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='members.member')),
            ],
            options={
                'ordering': ['team', 'bingo_item__position'],
            },
        ),
        migrations.AddConstraint(
            model_name='bingosubmission',
            constraint=models.UniqueConstraint(fields=('team', 'bingo_item'), name='unique_submission_per_team_item'),
        ),
    ]
