# Generated by Django 5.2.8 on 2025-12-01 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_bingosubmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingosubmission',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='bingo_photos/'),
        ),
        migrations.CreateModel(
            name='BingoSubmissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bingo_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='members.bingosubmission')),
            ],
        ),
    ]
