# Generated by Django 5.0.6 on 2025-12-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_bingosubmission_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingosubmission',
            name='rejected_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bingosubmission',
            name='status',
            field=models.CharField(choices=[('pending', '검토중'), ('approved', '승인'), ('rejected', '반려')], default='pending', max_length=20),
        ),
    ]
